const esbuild = require('esbuild');

const production = process.argv.includes('--production');
const watch = process.argv.includes('--watch');

/**
 * esbuild configuration for VS Code extension bundling
 * Following Microsoft's official VS Code extension bundling guidelines
 */
async function main() {
  const ctx = await esbuild.context({
    entryPoints: ['src/extension.ts'],
    bundle: true,
    format: 'cjs',
    platform: 'node',
    target: 'node18',
    outfile: 'dist/extension.js',
    external: ['vscode'],
    sourcemap: !production,
    minify: production,
    metafile: true,
    define: {
      'process.env.NODE_ENV': production ? '"production"' : '"development"',
    },
    banner: {
      js: '// VS Code Extension Bundle - Generated by esbuild',
    },
    logLevel: 'info',
  });

  if (watch) {
    console.log('[esbuild] Starting watch mode...');
    await ctx.watch();
  } else {
    console.log('[esbuild] Building extension...');
    const result = await ctx.rebuild();

    if (result.metafile) {
      console.log('[esbuild] Bundle analysis:');
      const analysis = await esbuild.analyzeMetafile(result.metafile);
      console.log(analysis);
    }

    await ctx.dispose();
    console.log('[esbuild] Build complete!');
  }
}

main().catch((error) => {
  console.error('[esbuild] Build failed:', error);
  process.exit(1);
});